AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AwsWhatsNew:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: handler.wambda_handwer
      CodeUri: ./
      Timeout: 200
      Environment:
        Variables:
          PostsTableName: !Ref AwsNewsRecentPostsTable
          PostRecencyThreshold: "7000"
      Events:
        CheckForNewPostsScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AwsNewsRecentPostsTable
        - Statement:
          -
            Effect: "Allow"
            Action:
              - ssm:GetParameters
              - ssm:GetParameter

            Resource:
              - '*'
  AwsNewsRecentPostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: guid
          AttributeType: S
      KeySchema:
        - AttributeName: guid
          KeyType: HASH

